spring.application.name=News-Aggregator-API
server.port=9292
spring.security.user.name=user
spring.security.user.password=$2a$11$C6j44UO4WGcM37Btj4ikP.973j4FqiYo7BSOsL0mc6CyMeAEx2J0e
#spring.datasource.url=jdbc:mysql://localhost:3306/newsaggregator
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:h2:mem:NewsAggregator;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect
spring.h2.console.enabled=true
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql= true
jwt.secret =my_super_secret_key_which_is_at_least_256_bits_long
jwt.expiration=28800000
# 8 hours in milliseconds
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
